services:
  isec:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
       MYSQL_DATABASE_USER: user
       MYSQL_DATABASE_PASSWORD: pass
       MYSQL_DATABASE_DB: db
       MYSQL_DATABASE_HOST: isec-db
       MYSQL_DATABASE_PORT: 3306

    ports:
      - 8000:8000

    depends_on:
      - isec-db

  isec-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_ROOT_USER: user

    ports:
      - 3306:3306

    volumes:
      - ./sql_data:/var/lib/mysql