services:
  isec:
    container_name: isec
    build:
      context: .
      dockerfile: Dockerfile

    environment:
       MYSQL_DATABASE_USER: user
       MYSQL_DATABASE_PASSWORD: pass
       MYSQL_DATABASE_DB: db
       MYSQL_DATABASE_HOST: isec-db
       MYSQL_DATABASE_PORT: 3306
       LOGFILE_PATH: log

    ports:
      - 8000:8000

    depends_on:
      - isec-db

  isec-db:
    container_name: isec-db
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_ROOT_USER: user
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

    ports:
      - 3306:3306

    volumes:
      - ./sql_data:/var/lib/mysql
