name: deploy

on:
  workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          host=${{secrets.SSH_IP}}
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts

      - name: Rm old files
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}  -t "rm -rf www/isec.smart-skills.pro/*"

      - name: copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "ISeC/app/"
          target: "www/isec.smart-skills.pro/"
          strip_components: 2

      - name: copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "ISeC/requirements.txt"
          target: "www/isec.smart-skills.pro/"
          strip_components: 1

      - name: install requirements
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}  -t "source /var/www/u0200264/data/flaskenv/bin/activate && pip install --upgrade pip && pip uninstall -y $(pip freeze) && pip install -r www/isec.smart-skills.pro/requirements.txt" 

      - name: install envs
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}  -t "sed -i 's|MYSQL_DATABASE_PLACEHOLDER|'${{secrets.MYSQL_DATABASE}}'|g' www/isec.smart-skills.pro/passenger_wsgi.py"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}  -t "sed -i 's|MYSQL_DATABASE_PASSWORD_PLACEHOLDER|'${{secrets.MYSQL_DATABASE_PASSWORD}}'|g' www/isec.smart-skills.pro/passenger_wsgi.py"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}  -t "sed -i 's|MYSQL_DATABASE_DB_PLACEHOLDER|'${{secrets.MYSQL_DATABASE_DB}}'|g' www/isec.smart-skills.pro/passenger_wsgi.py"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}  -t "sed -i 's|MYSQL_DATABASE_HOST_PLACEHOLDER|'${{secrets.MYSQL_DATABASE_HOST}}'|g' www/isec.smart-skills.pro/passenger_wsgi.py"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}  -t "sed -i 's|MYSQL_DATABASE_PORT_PLACEHOLDER|'${{secrets.MYSQL_DATABASE_PORT}}'|g' www/isec.smart-skills.pro/passenger_wsgi.py"
  

      - name: Restart app
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}  -t "touch www/isec.smart-skills.pro/.restart-app"
        
        
